// Mock data - Ropa Coreana de alta calidad - Importaciones Korean
export const koreanClothingProducts = [
  {
    id: 1,
    title: "Oversized Hoodie Korean Style",
    description: "Cómodo hoodie oversized de algodón 100% con estilo K-Fashion. Perfecto para uso casual y diario. Disponible en múltiples colores pastel. Importación directa desde Seoul.",
    price: 45000,
    image: "https://images.pexels.com/photos/19292024/pexels-photo-19292024.jpeg",
    category: "Sudaderas",
    gender: "Unisex",
    rating: { rate: 4.8, count: 245 },
  },
  {
    id: 2,
    title: "Wide Leg Cargo Pants",
    description: "Pantalones cargo de pierna ancha estilo coreano con bolsillos funcionales. Tela de algodón premium con detalles exclusivos. Cómodo y moderno. Tendencia 2024.",
    price: 52000,
    image: "https://images.pexels.com/photos/5365676/pexels-photo-5365676.jpeg",
    category: "Pantalones",
    gender: "Unisex",
    rating: { rate: 4.7, count: 198 },
  },
  {
    id: 3,
    title: "Korean Mini Crop Top",
    description: "Top corto elegante de tela stretch de alta calidad. Diseño minimalista coreano perfecto para outfits de primavera y verano. Ideal para cualquier ocasión.",
    price: 28000,
    image: "https://images.pexels.com/photos/11377698/pexels-photo-11377698.jpeg",
    category: "Tops",
    gender: "Mujer",
    rating: { rate: 4.6, count: 312 },
  },
  {
    id: 4,
    title: "Oversized Graphic Tee",
    description: "Camiseta oversized con gráficos K-pop únicos y diseños exclusivos. 100% algodón de alta calidad. Perfecta para coleccionistas de moda coreana.",
    price: 32000,
    image: "https://images.pexels.com/photos/7167968/pexels-photo-7167968.jpeg",
    category: "Camisetas",
    gender: "Unisex",
    rating: { rate: 4.9, count: 456 },
  },
  {
    id: 5,
    title: "Satin Button-Up Shirt",
    description: "Camisa satinada coreana con botones de perla genuina. Diseño elegante y versátil para eventos formales o uso casual. Material premium importado.",
    price: 58000,
    image: "https://images.pexels.com/photos/7139595/pexels-photo-7139595.png",
    category: "Blusas",
    gender: "Mujer",
    rating: { rate: 4.8, count: 287 },
  },
  {
    id: 6,
    title: "Leather Skirt Mini",
    description: "Falda mini de cuero sintético coreano con cierre lateral. Diseño audaz y moderno. Perfecta para looks de noche o salidas especiales.",
    price: 65000,
    image: "https://images.pexels.com/photos/34475570/pexels-photo-34475570.jpeg",
    category: "Faldas",
    gender: "Mujer",
    rating: { rate: 4.7, count: 189 },
  },
  {
    id: 7,
    title: "Pastel Cardigan Sweater",
    description: "Cardigan en colores pastel estilo coreano de lana suave. Perfecto para capas en primavera. Botones de cerámica artesanales. Importación original.",
    price: 48000,
    image: "https://images.pexels.com/photos/7280127/pexels-photo-7280127.jpeg",
    category: "Suéteres",
    gender: "Unisex",
    rating: { rate: 4.8, count: 334 },
  },
  {
    id: 8,
    title: "High Waist Denim Shorts",
    description: "Shorts de denim de talle alto con detalles rotos estilo vintage coreano. Tela de algodón premium. Comodísimos para verano.",
    price: 42000,
    image: "https://images.pexels.com/photos/12830687/pexels-photo-12830687.jpeg",
    category: "Shorts",
    gender: "Mujer",
    rating: { rate: 4.6, count: 267 },
  },
  {
    id: 9,
    title: "Oversized Blazer Korean",
    description: "Blazer oversized de lana con forro de seda coreana. Corte elegante y moderno. Ideal para looks profesionales o street style.",
    price: 72000,
    image: "https://images.pexels.com/photos/11770009/pexels-photo-11770009.jpeg",
    category: "Blusas",
    gender: "Mujer",
    rating: { rate: 4.9, count: 298 },
  },
  {
    id: 10,
    title: "Baggy Jeans Premium",
    description: "Jeans baggy de alta calidad con detalles de bordado coreano. Tela premium resistente. Perfecto para looks casuales modernos.",
    price: 55000,
    image: "https://images.pexels.com/photos/13391040/pexels-photo-13391040.jpeg",
    category: "Pantalones",
    gender: "Unisex",
    rating: { rate: 4.8, count: 421 },
  },
  {
    id: 11,
    title: "Silk Pajama Set",
    description: "Pijama de seda 100% coreana con detalles de botones. Suave y cómoda para dormir. Disponible en colores pastel.",
    price: 68000,
    image: "https://images.pexels.com/photos/5700115/pexels-photo-5700115.png",
    category: "Pijamas",
    gender: "Unisex",
    rating: { rate: 4.7, count: 156 },
  },
  {
    id: 12,
    title: "Trendy Bucket Hat",
    description: "Bucket hat coreano con bordados artesanales. Perfecto para eventos y looks casuales. Material resistente y duradero.",
    price: 35000,
    image: "https://images.pexels.com/photos/10887534/pexels-photo-10887534.jpeg",
    category: "Accesorios",
    gender: "Unisex",
    rating: { rate: 4.8, count: 378 },
  },
  {
    id: 13,
    title: "Striped Long Sleeve Shirt",
    description: "Camisa de manga larga con rayas al estilo coreano clásico. Tela de algodón suave y duradera. Perfecta para otoño e invierno. Diseño versátil.",
    price: 39000,
    image: "https://images.pexels.com/photos/3960374/pexels-photo-3960374.jpeg",
    category: "Camisetas",
    gender: "Unisex",
    rating: { rate: 4.7, count: 223 },
  },
  {
    id: 14,
    title: "Flowing Chiffon Blouse",
    description: "Blusa de gasa fluida con botones de madreperla. Estilo elegante y romántico coreano. Ideal para eventos especiales o uso diario chic.",
    price: 54000,
    image: "https://images.pexels.com/photos/16264350/pexels-photo-16264350.jpeg",
    category: "Blusas",
    gender: "Mujer",
    rating: { rate: 4.9, count: 345 },
  },
  {
    id: 15,
    title: "Ripped Tapered Pants",
    description: "Pantalones ajustados con roturas estratégicas al estilo K-fashion. Tela de jean premium importada. Tendencia actual de moda coreana.",
    price: 50000,
    image: "https://images.pexels.com/photos/7208448/pexels-photo-7208448.jpeg",
    category: "Pantalones",
    gender: "Unisex",
    rating: { rate: 4.8, count: 267 },
  },
  {
    id: 16,
    title: "Color Block Sweater",
    description: "Suéter de bloques de colores pastel. Diseño minimalista coreano muy trendy. Material de lana merino importado. Perfecto para primavera.",
    price: 52000,
    image: "https://images.pexels.com/photos/3833164/pexels-photo-3833164.jpeg",
    category: "Suéteres",
    gender: "Unisex",
    rating: { rate: 4.8, count: 298 },
  },
  {
    id: 17,
    title: "Pleated Midi Skirt",
    description: "Falda midi con pliegues coreanos. Largo elegante y sofisticado. Tela premium resistente. Ideal para looks formales o casuales.",
    price: 58000,
    image: "https://images.pexels.com/photos/9814512/pexels-photo-9814512.jpeg",
    category: "Faldas",
    gender: "Mujer",
    rating: { rate: 4.7, count: 178 },
  },
  {
    id: 18,
    title: "Oversized Denim Jacket",
    description: "Chaqueta de denim oversized con detalles de bordado coreano. Tela premium de algodón. Perfecta para cualquier look casual.",
    price: 64000,
    image: "https://images.pexels.com/photos/7048488/pexels-photo-7048488.jpeg",
    category: "Chaquetas",
    gender: "Unisex",
    rating: { rate: 4.9, count: 412 },
  },
  {
    id: 19,
    title: "Fit and Flare Dress",
    description: "Vestido acampanado estilo coreano vintage. Diseño elegante y favorecedero. Material de algodón con elastano. Perfecto para cualquier ocasión.",
    price: 62000,
    image: "https://images.pexels.com/photos/35710647/pexels-photo-35710647.jpeg",
    category: "Vestidos",
    gender: "Mujer",
    rating: { rate: 4.8, count: 334 },
  },
  {
    id: 20,
    title: "Vintage Wool Coat",
    description: "Abrigo de lana estilo vintage coreano. Corte elegante y cálido. Forro interior de seda de alta calidad. Perfecto para invierno.",
    price: 85000,
    image: "https://images.unsplash.com/photo-1616805714945-fae3d5b23809?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Abrigos",
    gender: "Mujer",
    rating: { rate: 4.9, count: 267 },
  },
  {
    id: 21,
    title: "Cotton Crop Hoodie",
    description: "Hoodie cropped de algodón 100%. Estilo deportivo coreano muy actual. Cómoda y versátil. Disponible en varios colores pastel.",
    price: 41000,
    image: "https://images.unsplash.com/photo-1578050665224-3a636f2b20b2?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    category: "Sudaderas",
    gender: "Mujer",
    rating: { rate: 4.7, count: 289 },
  },
];